### ISSUE TITLE
How can I create my own android app with this template?

### ISSUE THREAD

**Issue by sjuk** [eliasdorneles/beeware-android-template#4]
Thank you for the template. I've tried to find out how it works. But especially the java side does not make much sense to me. I've already read the issue about the documentation. But I don't get it. There are several initial questions.

How can I change the splash screen picture and the time it is shown on the screen?
Where do the "import android" statements in app.py reference to?
Am I able to design my own app with this template without coding java?

Thank you in advance.

**Comment by jvmaia** [comment]
I guess you can change the splash screen picture changing the splash.png files inside the android/res/drawable folders.
The "import android" statements in app.py reference to the android's API, you can see all of them here: [android developers guide](https://developer.android.com/reference/packages).
You can design your apps without coding java, as you can see on: [todo app](https://github.com/eliasdorneles/todoapp-voc).

You're welcome.

**Comment by sjuk** [comment]
Thank you for the information. I think I've to go deeper into the architecture of android apps. Perhaps there is something in the AndroidManifest.xml which can disable the splash screen. My goal is to see how much time the hello world app needs to start up. I've already tried to remove some "activity" stuff which looked like being the splash. But after that the app didn't start any more. I would be happy if there were some documentation about the things that must retain in the design files, and which can be adjusted to my needs.

**Comment by jvmaia** [comment]
The splash screen is located at android/res/drawable/splash_layout.xml, somethings are extremely new and we don't know how to do them yet. We don't have a documentation but we have a few tutorials here [wiki](https://github.com/eliasdorneles/beeware-android-template/wiki).
